image: openjdk:8

before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - apt-get install -y nodejs
  - gem install dpl

stages:
  - build
  - deploy

build:
  stage: build
  script: ./gradlew frontend bootJar
  artifacts:
    paths:
      - build/libs/pubslist-0.0.1-SNAPSHOT.jar

production:
  stage: deploy
  script:
    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_API_KEY
  only:
    - master
