image: timbru31/java-node:8-jdk

before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl

variables:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  POSTGRES_DB: drums

services:
  - postgres:9.5.0

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - ./gradlew frontend bootJar
  artifacts:
    paths:
      - build/libs/pubslist-0.0.1-SNAPSHOT.jar

production:
  stage: deploy
  script:
    - dpl --provider=heroku --app=pubslist --api-key=38c02116-1b82-40d8-8d3c-1fc039ee1e00
  only:
    - master
